internal/vote/vote.go
internal/vote/vote_test.go

Reject not started or analog polls

---

internal/vote/run_test.go
internal/vote/vote.go
internal/vote/vote_test.go

Disallow voting for anonymous

---

internal/vote/error.go
internal/vote/http_test.go

Rename msg to message in error messages

---

internal/vote/http.go

Set content-type header

---

internal/backends/postgres/postgres.go
internal/backends/postgres/schema.sql

@gsiv I have only a very small knowledge about SQL and postgres. Could you have a good look?

Create vote-schema for the postgres backend

---

go.mod
go.sum

that fixes the xadd bug
see #16
@peb-adr This should fix the xadd-bug. Could you test this? I have currently the problem, that I can not start the full system, so it is hard to test this feature.

Update to new autoupdate-version

---

go.mod
go.sum
internal/backends/postgres/postgres.go
internal/backends/redis/redis.go
internal/vote/http.go
internal/vote/vote.go
internal/vote/vote_test.go

Only request responsable backend
for votedID

Remove how has voted and the vote from log messages.

---

README.md
internal/vote/run.go

Add missing environment variables to

---

internal/backends/postgres/postgres.go
internal/backends/postgres/postgres_test.go
internal/vote/run.go

Support passwords with special chars

---

internal/vote/vote.go

Fix voted url

---

go.mod
go.sum
internal/vote/mock_test.go
internal/vote/vote.go
internal/vote/vote_preload_test.go
internal/vote/vote_test.go

Fix request-spam when starting a poll.
@emanuelschuetze The bug, that a poll is not created, should be fixed. But there could be other errors. The backend should handle them.

Fix many requests

---

internal/backends/redis/redis.go
internal/backends/redis/redis_test.go
internal/vote/http.go
internal/vote/http_test.go
internal/vote/mock_counter.go
internal/vote/run.go
internal/vote/vote.go
internal/vote/vote_test.go

Fix vote_count

---

.github/workflows/test.yml
Dockerfile
go.mod
go.sum

Update go to 1.18

---

internal/vote/http.go
internal/vote/http_test.go

Fix vote count reset

---

README.md
internal/backends/memory/memory.go
internal/backends/postgres/postgres.go
internal/backends/redis/redis.go
internal/backends/test/test.go
internal/vote/http.go
internal/vote/http_test.go
internal/vote/vote.go
internal/vote/vote_test.go

This changes the output of the `/system/voted?pid=1,2,3` route. The output is not a map from pollID to bool anymore, but a map from pollID to a list of userIDs.
@luisa-beerboom This can only be merged when the client is also changed. Please tell my when I can merge this.

Vote count for delegation

---

go.mod
go.sum
internal/vote/vote.go
internal/vote/vote_test.go

See: https://github.com/OpenSlides/openslides-client/issues/1512

Check meeting/users_enabe_vote_delegatoins

---

internal/backends/postgres/postgres.go
internal/backends/postgres/postgres_test.go
main.go

See https://github.com/OpenSlides/openslides-autoupdate-service/pull/622

Postgres connection

---

vote/http/http.go

@ostcar I suspect you forgot to adjust the registration of the `/health` handler when copy pasting those lines.
Please confirm this fix is correct and doesn't miss anything and merge if so.
I can confirm so far, that the vote service is starting correctly now (which it didn't on the current main)

fix probable copy paste mistake

---

backend/backend.go
environment.md
go.mod
go.sum
main.go
system_test/docker-compose.yml

@peb-adr this is the variables for the main postgres db. What about the vote-postgres.

Update environment variables

---

vote/vote.go
vote/vote_test.go

The old version used the meeting_user_id as user_id
Fixes #223

Fix voted for delegation

---

vote/http/http.go

Create a copy of the data instead using a reference

Fix handleAllVotedIDs
